# Generated by Django 5.0.7 on 2024-08-04 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='uploads/images')),
                ('location', models.CharField(max_length=150)),
                ('NbrOfparticipant', models.IntegerField()),
                ('duration', models.DateField()),
                ('Sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.sport')),
            ],
        ),
    ]
