# Generated by Django 5.0.7 on 2024-08-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0001_initial'),
        ('stade', '0002_stade_avis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='Sport',
            new_name='sport',
        ),
        migrations.AddField(
            model_name='annonce',
            name='stade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stade.stade'),
        ),
    ]
