# Generated by Django 5.0.7 on 2024-08-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='uploads/images')),
                ('location', models.CharField(max_length=150)),
                ('NbrOfparticipant', models.IntegerField()),
                ('decription', models.TextField()),
                ('open', models.IntegerField()),
                ('note', models.IntegerField(default=False)),
            ],
        ),
    ]
