# Generated by Django 5.0.7 on 2024-08-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0001_initial'),
        ('stade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stade',
            name='avis',
            field=models.ManyToManyField(to='avis.avis'),
        ),
    ]
