# Generated by Django 5.0.7 on 2024-08-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(blank=True, choices=[('CashPayment', 'Football'), ('OnLinePayment', 'Handball'), ('Basketball', 'Basketball'), ('Natation', 'Natation'), ('Equitation', 'Equitation'), ('Vollyball', 'Vollyball'), ('Bebenageur', 'Bebenageur')], max_length=20, null=True)),
            ],
        ),
    ]
