# Generated by Django 5.0.7 on 2024-08-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paiement',
            new_name='Reclamation',
        ),
    ]
