# Generated by Django 5.0.7 on 2024-08-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_rename_sport_annonce_sport_annonce_stade'),
        ('paiement', '0001_initial'),
        ('reclamation', '0002_rename_paiement_reclamation'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='annonce',
            field=models.ManyToManyField(to='annonce.annonce'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='paiement',
            field=models.ManyToManyField(to='paiement.paiement'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reclamation',
            field=models.ManyToManyField(to='reclamation.reclamation'),
        ),
    ]
