# Generated by Django 5.0.7 on 2024-08-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_annonce_reservation_paiement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='EndTime',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='ResDate',
            new_name='resDate',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='StartTime',
            new_name='startTime',
        ),
    ]
